name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            os: linux
            suffix: amd64
          - arch: arm
            os: linux
            suffix: arm
          - arch: arm64
            os: linux
            suffix: arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22
          cache: true

      - name: Build ${{ matrix.arch }}
        run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} GO111MODULE=on go build -a -installsuffix nocgo -v -o traefik-forward-auth_${{ matrix.suffix }} ./cmd

      - name: Upload ${{ matrix.arch }} release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: traefik-forward-auth_${{ matrix.suffix }}
          asset_name: traefik-forward-auth_${{ matrix.suffix }}
          asset_content_type: application/octet-stream